### PR TITLE
Remove local profile

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by geoand** [comment]
Is this a duplicate of #24 ?

**Comment by gytis** [comment]
Cherry-pick on a redhat branch. @geoand do you know if there is a way to have one PR for both branches?

**Comment by geoand** [comment]
@gytis Sorry, I didn't see that :)

I'm not aware of any such feature unfortunately

**Comment by gytis** [comment]
Seems that rhoar-bot doesn't have correct repositories configured as it's searching for `me.snowdrop:spring-boot-bom:pom:1.5.10.SP2-redhat-2` in Maven Central

**Pull request merged**
