### PR TITLE
[SB-100] Use secret instead of hard-coded credentials

### PR DESCRIPTION
**Pull request by gytis**
https://issues.jboss.org/browse/SB-100

### CODE REVIEW

**Comment by cmoulliard** [comment]
@metacosm The password is still defined as clear text within the secret resource. It should be good to encrypt it

```
oc create secret generic my-database-secret --from-literal=username='luke',password='secret'
...
oc get secrets/my-database-secret -o yaml
apiVersion: v1
data:
  password: c2VjcmV0
  username: bHVrZQ==
kind: Secret
metadata:
  name: my-database-secret
type: Opaque
...
```

**Comment by gytis** [comment]
@cmoulliard I wanted to align it with other runtimes and have the same set of fabric8 configurations.

**Comment by metacosm** [comment]
There's something to be said about consistency with other runtimes indeed. We should try to convince the other runtimes to use the encrypted versions, though, since we want to advertise best practices.

**Comment by cmoulliard** [comment]
Can one of you send email to obsidian mailing to request to align secret using encrypted/base64 password ?

**Pull request merged**
