### PR TITLE
DO NOT MERGE: Update to work with OSIO

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by lordofthejars** [comment]
This should not be merged against master but against a branch called `osio-align-with-redhat`

**Comment by geoand** [comment]
@gytis You have done some stuff on OSIO before (while I have not :P ), do you have any comments on this? 

I'm sure what  @lordofthejars has done is perfect, but just trying to be on the safe side here :)

**Comment by metacosm** [comment]
Honestly, I don't think that any of us are able to check the validity of this change :)

**Comment by geoand** [comment]
So should we merge it into `osio-align-with-redhat`?

**Comment by lordofthejars** [comment]
I have tested manually today at OSIO and it worked perfectly, but of course, I understand your concerns.

**Comment by gytis** [comment]
I'd say just trust the lord :)

**Comment by geoand** [comment]
Well like @metacosm said we have close to zero experience with OSIO, but that shouldn't be a problem, since the change doesn't affect the booster in any other way.

@metacosm I propose we go ahead and merge it, WDYT?

**Comment by metacosm** [comment]
@lordofthejars is that change requested by someone from the OSIO team?

**Comment by bartoszmajsak** [comment]
I can certify as we did this thing together ;) The broader discussion we should have though is why there is a separated branch. But that's for later

**Comment by metacosm** [comment]
So this should be included in a new `osio-align-with-redhat` branch? I thought that OSIO was only using the productized versions of the boosters but this PR is done off of `master`, though, the `redhat` branch is currently lagging behind `master` so this is probably fine…

**Comment by metacosm** [comment]
@bartoszmajsak ok.

**Comment by metacosm** [comment]
@bartoszmajsak @lordofthejars can you check the new branch (https://github.com/snowdrop/spring-boot-crud-booster/tree/osio-align-with-redhat), please to see if it conforms to what you expected?

**Comment by lordofthejars** [comment]
@metacosm Yes that's perfect for now.

**Comment by metacosm** [comment]
Branch was created so closing for now, re-open if needed!

**Comment by metacosm** [comment]
@lordofthejars @bartoszmajsak who will be responsible for maintaining this branch, though (i.e. make sure that latest change are applied, booster is released, catalog is updated accordingly)?

**Comment by metacosm** [comment]
@bartoszmajsak No, the code is tagged and then that tag is referenced in https://github.com/fabric8-launcher/launcher-booster-catalog under the proper hierarchy with an appropriate YAML configuration (if we want that booster version to appear in the RHOAR launcher, that is)

**Comment by bartoszmajsak** [comment]
That's what I thought. Thanks for the clarification.

**Comment by metacosm** [comment]
@bartoszmajsak Note also that there is already another booster that has an OSIO-specific branch (https://github.com/snowdrop/spring-boot-configmap-booster/tree/osio) which has a different name than the one we created for this booster. We're not updating that branch either as we consider that the change in the implementation required to work with OSIO doesn't reflect how the configmap mission should be implemented and therefore is a temporary branch to be removed when OSIO properly supports the scenario. See https://github.com/snowdrop/spring-boot-configmap-booster/pull/43 for a discussion on this particular topic and my point of view on the issue… :)

**Pull request closed without merging**
